/*

SQLite

*/

-- TABLAS
CREATE TABLE IF NOT EXISTS EMPLEADO (
    rut NUMBER PRIMARY KEY,
    NombreApellidos VARCHAR2(70),
    num_Sexo NUMBER,
    direccion VARCHAR2(70),
    telefono VARCHAR2(12),
    num_Cargo NUMBER,
    fechaIngreso DATE,
    FOREIGN KEY (num_Sexo) REFERENCES SEXO(codSexo)
);

CREATE TABLE IF NOT EXISTS CARGO (
    codCargo NUMBER PRIMARY KEY,
    nombreCargo VARCHAR2(30),
    num_Departamento NUMBER,
    FOREIGN KEY (num_Departamento) REFERENCES DEPARTAMENTO(codDepartamento)
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
    codDepartamento NUMBER PRIMARY KEY,
    Nombre VARCHAR2(30),
    num_Area NUMBER,
    FOREIGN KEY (num_Area) REFERENCES AREA(codArea)
);

CREATE TABLE IF NOT EXISTS AREA (
    codArea NUMBER PRIMARY KEY,
    Nombre VARCHAR2(30)
);

CREATE TABLE IF NOT EXISTS SEXO (
    codSexo NUMBER PRIMARY KEY,
    Nombre VARCHAR2(20)
);

CREATE TABLE IF NOT EXISTS CARGA_FAMILIAR (
    rut_carga NUMBER PRIMARY KEY,
    NombresApellidos VARCHAR2(30),
    num_Empleado NUMBER,
    num_Relacion NUMBER,
    num_Sexo NUMBER,
    FOREIGN KEY (num_Empleado) REFERENCES EMPLEADO(rut),
    FOREIGN KEY (num_Relacion) REFERENCES RELACION(codRelacion),
    FOREIGN KEY (num_Sexo) REFERENCES SEXO(codSexo)
);

CREATE TABLE IF NOT EXISTS RELACION (
    codRelacion NUMBER PRIMARY KEY,
    Nombre VARCHAR2(20)
);

CREATE TABLE IF NOT EXISTS CONTACTO_EMERGENCIA (
    codContacto NUMBER PRIMARY KEY,
    NombreApellido VARCHAR2(30),
    num_Relacion NUMBER,
    num_Sexo NUMBER,
    num_Empleado NUMBER,
    contacto VARCHAR2(30),
    FOREIGN KEY (num_Relacion) REFERENCES RELACION(codRelacion),
    FOREIGN KEY (num_Sexo) REFERENCES SEXO(codSexo),
    FOREIGN KEY (num_Empleado) REFERENCES EMPLEADO(rut)
);

CREATE TABLE IF NOT EXISTS CREDENCIAL (
    codCredencial NUMBER PRIMARY KEY,
    IDENT NUMBER,
    Usuario VARCHAR2(20),
    Clave VARCHAR2(70)
);





/*

SQL Puro

*/

-- TABLAS
CREATE TABLE IF NOT EXISTS EMPLEADO (
    RUT Number,
    NombresApellidos VARCHAR2(70),
    num_Sexo NUMBER,
    direccion VARCHAR2(70),
    telefono VARCHAR2(12),
    num_Cargo NUMBER,
    fechaIngreso DATE,
    num_Contacto NUMBER
);

CREATE TABLE IF NOT EXISTS CARGO (
    codCargo NUMBER,
    nombreCargo VARCHAR2(30),
    num_Departamento NUMBER
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
    codDepartamento NUMBER,
    Nombre VARCHAR2(30),
    num_Area NUMBER
);

CREATE TABLE IF NOT EXISTS AREA (
    codArea NUMBER,
    Nombre VARCHAR2(30)
);

CREATE TABLE IF NOT EXISTS SEXO (
    codSexo NUMBER,
    Nombre VARCHAR2(20)
);

CREATE TABLE IF NOT EXISTS CARGA_FAMILIAR (
    rut_carga NUMBER,
    NombresApellidos VARCHAR2(30),
    num_Empleado NUMBER,
    num_Relacion NUMBER,
    num_Sexo NUMBER
);

CREATE TABLE IF NOT EXISTS RELACION (
    codRelacion NUMBER,
    Nombre VARCHAR2(20)
);

CREATE TABLE IF NOT EXISTS CONTACTO_EMERGENCIA (
    codContacto NUMBER,
    NombreApellido VARCHAR2(30),
    num_Relacion NUMBER,
    num_Sexo NUMBER,
    num_Empleado NUMBER,
    contacto VARCHAR2(30)
);

CREATE TABLE IF NOT EXISTS CREDENCIALES (
    codCredencial NUMBER,
    IDENT NUMBER,
    Usuario VARCHAR2(20),
    Clave VARCHAR2(70)
);


-- ALTER: PKs
ALTER TABLE EMPLEADO
ADD CONSTRAINT PK_EMPLEADO_rut PRIMARY KEY (rut);

ALTER TABLE CARGO
ADD CONSTRAINT PK_CARGO_codCargo PRIMARY KEY (codCargo);

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PK_DEPARTAMENTO_codDepartamento PRIMARY KEY (codDepartamento);

ALTER TABLE AREA
ADD CONSTRAINT PK_AREA_codArea PRIMARY KEY (codArea);

ALTER TABLE SEXO
ADD CONSTRAINT PK_SEXO_codSexo PRIMARY KEY (codSexo);

ALTER TABLE CARGA_FAMILIAR
ADD CONSTRAINT PK_CARGA_FAMILIAR_rut_carga PRIMARY KEY (rut_carga);

ALTER TABLE RELACION
ADD CONSTRAINT PK_RELACION_codRelacion PRIMARY KEY (codRelacion);

ALTER TABLE CONTACTO_EMERGENCIA
ADD CONSTRAINT PK_CONTACTO_EMERGENCIA_codContacto PRIMARY KEY (codContacto);

ALTER TABLE CREDENCIALES
ADD CONSTRAINT PK_CREDENCIALES_codCredencial PRIMARY KEY (codCredencial);


-- ALTER: FKs

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_num_Sexo
FOREIGN KEY (num_Sexo) REFERENCES SEXO(codSexo);

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_num_Cargo
FOREIGN KEY (num_Cargo) REFERENCES CARGO(codCargo);

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_num_Contacto
FOREIGN KEY (num_Contacto) REFERENCES CONTACTO_EMERGENCIA(codContacto);

ALTER TABLE CARGO
ADD CONSTRAINT FK_CARGO_num_Departamento
FOREIGN KEY (num_Departamento) REFERENCES DEPARTAMENTO(codDepartamento);

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT FK_DEPARTAMENTO_num_Area
FOREIGN KEY (num_Area) REFERENCES AREA(codArea);

ALTER TABLE CARGA_FAMILIAR
ADD CONSTRAINT FK_CARGA_FAMILIAR_num_Empleado
FOREIGN KEY (num_Empleado) REFERENCES EMPLEADO(RUT);

ALTER TABLE CARGA_FAMILIAR
ADD CONSTRAINT FK_CARGA_FAMILIAR_num_Relacion
FOREIGN KEY (num_Relacion) REFERENCES RELACION(codRelacion);

ALTER TABLE CARGA_FAMILIAR
ADD CONSTRAINT FK_CARGA_FAMILIAR_num_Sexo
FOREIGN KEY (num_Sexo) REFERENCES SEXO(codSexo);

ALTER TABLE CONTACTO_EMERGENCIA
ADD CONSTRAINT FK_CONTACTO_EMERGENCIA_num_Relacion
FOREIGN KEY (num_Relacion) REFERENCES RELACION(codRelacion);

ALTER TABLE CONTACTO_EMERGENCIA
ADD CONSTRAINT FK_CONTACTO_EMERGENCIA_num_Sexo
FOREIGN KEY (num_Sexo) REFERENCES SEXO(codSexo);

ALTER TABLE CONTACTO_EMERGENCIA
ADD CONSTRAINT FK_CONTACTO_EMERGENCIA_num_Empleado
FOREIGN KEY (num_Empleado) REFERENCES EMPLEADO(rut);

ALTER TABLE CREDENCIALES
ADD CONSTRAINT FK_CREDENCIALES_num_Empleado
FOREIGN KEY (IDENT) REFERENCES EMPLEADO(rut);


-- 
